DROP TABLE IF EXISTS
    "PRODUCT"
;

CREATE TABLE "PRODUCT" (
    "ID"            SERIAL PRIMARY KEY,
	"NAME"          VARCHAR(255) NOT NULL UNIQUE,
    "DESCRIPTION"   TEXT,
	"PRICE"		    DECIMAL NOT NULL
);