DROP TABLE IF EXISTS
    "PRODUCT",
    "SHIPPING"
;

CREATE TABLE "PRODUCT" (
    "ID"            SERIAL PRIMARY KEY,
	"NAME"          VARCHAR(255) NOT NULL UNIQUE,
    "DESCRIPTION"   TEXT,
	"PRICE"		    DECIMAL NOT NULL
);

CREATE TABLE "SHIPPING" (
    "ID"            SERIAL PRIMARY KEY,
	"PRICE"         DECIMAL NOT NULL,
    "PACKAGE"       INTEGER UNIQUE NOT NULL
);