name: Azure deployment
env:
  AZURE_WEBAPP_NAME: 'MyStore'
  AZURE_WEBAPP_PACKAGE_PATH: '.'

on:
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '6.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ./back

      - name: Build
        run: dotnet build ./back --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./back/MyStore.Web -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: '{{ env.AZURE_WEBAPP_NAME }}'
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

  deploy:
     runs-on: ubuntu-latest
     needs: build
     environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

     steps:

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: '{{ env.AZURE_WEBAPP_NAME }}'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '{{ env.AZURE_WEBAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'